ratechecker/views.py

Fixes bug with 10-1 not returning any data

remove "-1" from the end of arm type value

---

ratechecker/views.py

Since our data provider decided to use this filter too

use .5 limit in both API results and testing of data loads

---

README.md

Added more information about each parameter and more details about accepted values.

Update API Parameters Table

---

ratechecker/tests/__init__.py
ratechecker/tests/test_views.py
ratechecker/tests/test_views_ratecheckerparameters.py

Trying to improve the rate checker code coverage.
...Have not looked at loading data coverage yet.
Doing a pull request early to check the current coverage.  Will mention when ready for merge.

Improve Ratechecker code coverage

---

README.md

Coverage status should point to CFPB Master

Coverage status was pointing to the wrong location

---

ratechecker/management/commands/load_daily_data.py

This may be the reason the loading script doesn't work.

Fix broken Load Daily Data

---

README.md
ratechecker/management/commands/load_daily_data.py
requirements-test.txt

This will remove all mysql reference for testing.  No longer need mysql installation for testing

Issue#55: Remove mysql exception

---

README.md
oahapi/oahapi/urls.py

This fixes the comments on the routing and also the file that included the routing

Fix incorrect routing for OaH

---

mortgageinsurance/tests/test_commands_load_mortgage_insurance.py
mortgageinsurance/tests/test_views.py

Added a few more tests to make the test coverage more complete.

Add more mortgage insurance tests

---

.coveragerc
.travis.yml
countylimits/management/commands/load_county_limits.py
countylimits/tests.py
ratechecker/tests/test_load_daily_data_command.py

Please coveralls

---

ratechecker/views.py

@amymok give it a run on local box, I got 4-6x faster execution, but sometimes it runs just as slow as before and I can't yet figure out what's causing it

Fix OaH API performance problem

---

ratechecker/management/commands/load_daily_data.py
ratechecker/tests/test_load_daily_data_command.py

When there are scenarios mismatch, this will now show the expected and actual results in the output.
- Added expected and actual results for message output
- @fna
Please merge this one first, so we have the tests fixed (I will rerun https://github.com/cfpb/owning-a-home-api/pull/89 afterward to see if it fixes the problem).

Load_Daily_Data: Add more output info for failed scenarios - To Master Branch

---

countylimits/tests.py
countylimits/views.py

This change is for production branch.
- If state is not found in DB, it will now return an error statement instead of echo back the parameters
@fna

CountyLimit (Production): Invalid State should return 400

---

countylimits/tests.py
countylimits/views.py

- If state is not found in DB, it will now return an error statement instead of echo back the parameters
@fna
- Need to create the same PR for current production branch

CountyLimit: Invalid State should return 400

---

CHANGELOG.md
setup.py

This PR updates `CHANGELOG.md` and `setup.py` in preparation for an 0.9.95 release.

Prep for 0.9.95 release

---

countylimits/data_collection/gather_county_data.py

Trivial change to test Travis release build.

sort imports in script

---

docs/api.md

Restore proper footnote coding

---

setup.py

This change updates the pin of django-localflavor to be inclusive of the latest release.

Update pin of django-localflavor

---

setup.py

The unicodecsv package is not used in this app.

Remove unicodecsv from setup.py dependencies

---

countylimits/models.py
countylimits/tests.py
countylimits/views.py
ratechecker/management/commands/load_daily_data.py
ratechecker/models.py
ratechecker/tests/test_views.py
ratechecker/tests/test_views_rate_query.py
ratechecker/views.py
setup.py
tox.ini

Support Django 3.2

---

.github/workflows/test.yml
README.md
tox.ini

This change updates our base Python required to 3.8.

Update to Python 3.8

---

countylimits/data_collection/gather_county_data.py
countylimits/management/commands/load_county_limits.py
countylimits/tests.py
ratechecker/dataset.py
ratechecker/tests/management/commands/test_load_daily_data.py
ratechecker/tests/test_dataset.py
ratechecker/tests/test_loader.py
ratechecker/tests/test_validation.py
ratechecker/tests/test_views.py
ratechecker/views.py
settings_for_testing.py
setup.py
tox.ini

This PR updates this app's dependencies and includes support for Django 4.2.

Update dependencies and support Django 4.2
