cfpb/owning-a-home-api

- ratechecker/management/commands/load_daily_data.py
Because our data provider has trouble communicating us the exact logic it uses to calculate test results we decided not to let it stop us from loading data.
> continue loading data even if some scenarios do not match

- README.md
Remove the unnecessary step to make a directory.  Because it was creating another layer of folders, (oah_api/oah_api/oah_api in order to access settings.py and other files)
> Remove commands to create project

- README.md
the params table for mortgage insurance API has the wrong info for 'required' condition, I updated to `loan_type`
> fix 'va' param documentation for mortgage insurance API

- README.md
@cfpb, I've corrected a typographical error in the documentation of the [owning-a-home-api](https://github.com/cfpb/owning-a-home-api) project. You should be able to merge this pull request automatically. However, if this was intentional or if you enjoy living in linguistic squalor, please let me know and [create an issue](https://github.com/thoppe/orthographic-pedant/issues/new) on my home repository.
> Fixed typographical error, changed adminstration to administration in README.

- ratechecker/ratechecker_parameters.py
- ratechecker/tests/test_views_ratecheckerparameters.py
This makes sure no script tags can be included in api error messages.
An api error message on a rejected value could include a script tag:
Rather than hack the DRF error framework, this defangs any returned error messages:
@cfpb/cfgov-backends 
@lfatty
> Make endpoint error messages safe for round-trips

- ratechecker/management/commands/load_daily_data.py
- ratechecker/tests/test_load_daily_data_command.py
The purpose of this change is to allow us to run the load_daily_data process in environments that have multiple databases.  Right now, the command will run against whatever is set up as 'default'.
---
Update the load_daily_data management command to support an optional override of the target database.  The change includes a refactor to Django 1.8+ style argument parsing.
This PR was heavily influenced by the code for dbshell: https://github.com/django/django/blob/3c447b108ac70757001171f7a4791f493880bf5b/django/core/management/commands/dbshell.py
@rosskarchner @higs4281 @amymok
> load_daily_data optional --database argument

- CHANGELOG.md
- ratechecker/ratechecker_parameters.py
- ratechecker/tests/test_views_ratecheckerparameters.py
Passing a 'price' parameter of 0 causes a `DivisionByZero` exception. This change modifies the API to change `price=0` to `price=1`. This solely prevents this case in the API and has no effect on the application frontend which already enforces a minimum price.
We've been a fair number of 500 errors like this recently.
<details>
<summary>Here's an example stack trace</summary>
```
Internal Server Error: /oah-api/rates/rate-checker Traceback (most recent call last):
...
File "/srv/cfgov/current/venv/lib/python2.7/site-packages/ratechecker/views.py", line 171, in rate_checker
if serializer.is_valid():
File "/srv/cfgov/current/venv/lib/python2.7/site-packages/rest_framework/serializers.py", line 191, in is_valid
self._validated_data = self.run_validation(self.initial_data)
File …
```
> Enforce non-zero price in ratechecker API

- CHANGELOG.md
- ratechecker/tests/test_views.py
- ratechecker/urls.py
- ratechecker/views.py
- requirements/test.txt
This commit adds a new ratechecker API endpoint at `/rate-checker/status` that returns a JSON blob with a `"load"` key containing the timestamp of the most recent data load, e.g.
```sh
$ curl -H "Accepts: application/json" http://localhost:8000/oah-api/rates/rate-checker/status
{"load":"2017-02-14T05:00:00Z"}
```
If no data exists, it returns
```sh
$ curl -H "Accepts: application/json" http://localhost:8000/oah-api/rates/rate-checker/status
{"load":null}
```
This new endpoint uses Django Rest Framework so has the nice browseable UI when accessed via a browser:
This will be useful for external services checking the recency of available data.
To run unit tests within this repo (make sure you `pip install -r requirements/test.txt`):
```sh
(owning-a-home-api) $ ./pytest.sh …
```
> Add new API endpoint to get ratechecker data load timestamp 

- ratechecker/models.py
Adds the new property type "CASHOUT-REFI" for data loads.
Testing:
- I went into Jenkins and retrieved the most recent zip file from the workspace
- Run db setup, particularly `./manage.py load_daily_data ratechecker/data/sample.zip`
- Process should complete without errors
> Add cashout refi

- countylimits/data_collection/county_data_monitor.py
This script encountered a request that returned a 403 "Forbidden" status code, but continued on, eventually throwing an unhelpful parsing error.
This will raise a more understandable error before unleashing beautifulsoup, if we encounter such a problem again.
cc @acrewdson
> Add 'raise_for_status' to capture status errors for troubleshooting

- .travis.yml
In trying to understand why Travis attaches a wheel to this repo with '.dev0+sha' in the name we noticed that this form first makes it appearance [here](https://travis-ci.org/cfpb/owning-a-home-api#L735-L736) in the Travis build.
This PR tests whether setting the Travis config to `skip_cleanup: false` gets rid of this egg reference.
> test if cleanup gets rid of old egg info

- docs/mysql.md
- requirements/test.txt
- settings_for_testing.py
This change adds support for using the `DATABASE_URL` environment variable to specify Django's test database, based on the [dj-database-url](https://github.com/kennethreitz/dj-database-url) package.
It lets you run tests against e.g. Postgres:
```sh
$ DATABASE_URL=postgres://user@localhost/db ./pytest.sh
```
(Note that this will require first creating a local database and `pip install`ing `psycopg2==2.7.3.2`.)
It adds `dj-database-url==0.4.2` to the test requirements as that matches the current version in cfgov-refresh.
- @chosak  and I paired on this. This is part of the work being done on platform#2567 to add Postgres compatibility to all cf.gov code. We're hoping to use this pattern with all satellite apps to make database testing easier everywhere.
> Support optional testing of other databases

- requirements/base.txt
- requirements/test.txt
This change only affects this repo, but will keep Jenkins jobs from
hitting import failures.
The Jenkins jobs install base requirements and then issue manage.py
commands, but the repo's manage.py file uses settings_for_testing.py.
Since the requirements files only affect this repo, it's most efficient
to move the db requirement into base.txt and leave the jenkins jobs
alone.
> Move dj-database-url requirement to base

- ratechecker/dataset.py
Handle temporary absence of fees data by skipping fees data load when fees file is not found.
> Handle missing fees data

- CHANGELOG.md
- setup.py
- tox.ini
- Remove Django 1.8 support from `setup.py` and `tox.ini`
- Allow flexible version of djangorestframework - any version that supports Django 1.11
> Remove Django 1.8 support

- docs/api.md
- ratechecker/dataset.py
- ratechecker/tests/test_views_rate_query.py
- ratechecker/views.py
The rate checker acquires its date stamp from the first entry in the region table.
If a request occurred while the table was being refreshed, the view would find no first entry and
raise an IndexError, causing a server error.
This allows the view to complete without a date stamp during the brief time regions are not available.
PR includes some pep8 fixes.
> Prevent IndexError when building date stamp

- docs/api.md
Tweak to api docs to make the `ltv` footnote reference work with a fragment identifier.
> fix footnote reference

- .travis.yml
- README.md
- countylimits/data_collection/county_data_monitor.py
- countylimits/data_collection/gather_county_data.py
- countylimits/management/commands/load_county_limits.py
- countylimits/models.py
- countylimits/tests.py
- ratechecker/dataset.py
- ratechecker/management/commands/load_daily_data.py
- ratechecker/tests/helpers.py
- ratechecker/tests/test_dataset.py
- ratechecker/tests/test_views.py
- ratechecker/views.py
- setup.py
- tox.ini
This PR adds (almost all that is needed for) Python 3 support for this project. The unit tests run via tox are now configured to test against both Python 2.7 and Python 3.6. The wheel built from releases of this project is now built as `--universal`.
Support for Python 2.6 has also been removed.
There's only one unit test left that fails, that relates to our use of [unicodecsv](https://pypi.org/project/unicodecsv/). Unfortunately this library doesn't seem to support Python 3.6, and [appears to be abandoned](https://github.com/jdunck/python-unicodecsv/pull/85#issuecomment-467981537).
I tried looking into this failure, but I thought it might be better to defer to @higs4281's experience here. Any idea what the proper incantation of `'rb'` or `'rU'` needs to be to make this work with Python …
> Add Python 3 support to this repository 

- .travis.yml
- README.md
- countylimits/data_collection/gather_county_data.py
- countylimits/models.py
- countylimits/tests.py
- ratechecker/tests/helpers.py
- setup.py
- tox.ini
Since we're removing Python 2 compatibility from the consumerfinance.gov family of projects, remove python 2 from this repo.
- Remove all references to `six`
- Remove Python 2 from the Tox testing matrix
- Remove Python 2 from Travis
> Remove python 2

- .travis.yml
Since we no longer support python 2, we no longer need to create a wheel
that is python 2 compatible.
> Don't create universal wheels

- setup.py
This change will pin Django Rest Framework to >=3.9.1 to detail with a security issue that GitHub has flagged, and <4.0 which is the the exclusive maximum that Wagtail 2.8 currently pins (which we have to be compatible with when owning-a-home-api gets pulled into cfgov-refresh).
> Pin Django Rest Framework to >=3.9.1,<4.0

- countylimits/views.py
This change replaces our use of the term "whitelist" with "allowlist."
"Allowlist" and "blocklist" have a clarity of meaning for which "whitelist" and "blacklist" rely on metaphor, and metaphor can encode in thought and language both historic and current forms of domination. This is an attempt to rid our codebase of two of those metaphors.
> Replace use of "whitelist" with "allowlist"

- setup.py
When setting `unittest-future` to use Wagtail 2.9 an error was logged due to the version of beautifulsoup4.
Error: version conflict: beautifulsoup4 4.8.2 (.tox/unittest-current/lib/python3.6/site-packages) <-> beautifulsoup4<4.7,>=4.5.0 (from owning-a-home-api==0.15.0->-r cfgov-refresh/requirements/libraries.txt (line 45))
This simple update to `setup.py` makes the following change from 4.7 to 4.9.
To test this change run tox and you would see the following results:
```
lint installdeps: black, flake8, isort
lint installed: appdirs==1.4.4,attrs==19.3.0,beautifulsoup4==4.8.2,black==19.10b0,certifi==2020.6.20,chardet==3.0.4,click==7.1.2,coverage==4.5.4,dj-database-url==0.5.0,Django==2.2.13,django-cors-headers==3.4.0,django-localflavor==3.0.1,djangorestframework==3.11.0,flake8==3.8.3,idna==2. …
```
> Update beautifulsoup4 version to support Wagtail 2.9

- ratechecker/dataset.py
- ratechecker/ratechecker_parameters.py
- ratechecker/tests/management/commands/test_load_daily_data.py
- ratechecker/tests/test_dataset.py
- ratechecker/tests/test_loader.py
- ratechecker/tests/test_validation.py
- ratechecker/tests/test_views.py
- ratechecker/views.py
- setup.py
- tox.ini
Removed `not_skip` and `recursive` from `tox.ini` to fix
TypeError: __init__() got an unexpected keyword argument 'not_skip'
Prior to version 5.0.0, isort wouldn't automatically traverse directories. The --recursive option was necessary to tell it to do so. In 5.0.0 directories are automatically traversed for all Python files, and as such this option is no longer necessary and should simply be removed.
In an earlier version isort had a default skip of __init__.py. To get around that many projects wanted a way to not skip __init__.py or any other files that were automatically skipped in the future by isort. isort no longer has any default skips, so if the value here is __init__.py you can simply remove the setting.
https://timothycrosley.github.io/isort/docs/upgrade_guides/5.0.0/
Short …
> Updates to support isort 5.0

- settings_for_testing.py
We've removed CSRF from non-authenticated paths in https://github.com/cfpb/consumerfinance.gov/pull/6366. The PR removes the CSRF middleware from the standalone testing settings.
> Remove CSRF middleware in settings
